title: TCG Rio Preto e Região
email: contato@johnywalves.com.br
description: >-
  Coleção de informações sobre eventos e locais de suporte da 
  comunidade Trading Card Game (TCG) em São José do Rio Preto
  e Região
url: https://tcgrp.com.br
baseurl: ""
github_username: johnywalves

# Config
future: true
permalink: /:title
timezone: America/Sao_Paulo

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
