title: TCG Rio Preto e Região
email: contato@johnywalves.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Coleção de informações sobre eventos e locais de suporte da comunidade TCG
  em São José do Rio Preto e Região
baseurl: "" # the subpath of your site, e.g. /blog
url: tcgrp.com.br
github_username: johnywalves

# Config
future: true
permalink: /:title.html
timezone: America/Sao_Paulo

# Build settings
plugins:
  - jekyll-feed
